### ISSUE TITLE
Move php-cli from required to suggested in composer.

### ISSUE THREAD

**Issue by DigiLive** [JBlond/php-diff#55]
I think using the library at an cli is another (secondary) use case.
Most will use the HTML or the Text renderers which will not require the php-cli package.
Therefor I suggest moving the package from the required section to the suggested section of `composer.json`

Calling the classes of php-cli will throw an exception when the package isn't installed.
These can be caught by the scripts in the stack trace. 

```yaml
{
    "require": {
        "php": ">=7.2",
        "ext-mbstring": "*",
    },
    "suggest": {
        "jblond/php-cli": "^1.0"
    }
}
```
